SALib/SALib

SALib/analyze/delta.py, SALib/analyze/dgsm.py, SALib/analyze/fast.py, SALib/analyze/morris.py, SALib/analyze/sobol.py, SALib/analyze/sobol_rbf.py, SALib/sample/fast_sampler.py, SALib/sample/finite_diff.py, SALib/sample/latin.py, SALib/sample/morris.py, SALib/sample/saltelli.py, SALib/sample/sobol_sequence.py, SALib/tests/test_analyze_morris.py, SALib/tests/test_regression.py, SALib/tests/test_sobol.py, examples/delta/delta.py, examples/dgsm/dgsm.py, examples/fast/fast.py, examples/morris/morris.py, examples/sobol/sobol.py, examples/sobol_rbf/sobol_rbf.py, examples/sobol_rbf/sobol_rbf.sh
This set of changes adds the "problem dictionary" input to all sampling and analysis methods, to optionally avoid creating a parameter file.
It also changes the analysis methods to accept numpy matrices directly rather than filenames. This should make it easier to do the whole analysis in python without reading/writing files.
=> Problem dict and cleanup

setup.py
Work around for bug #27 which only occurs using version of numpy 1.7 and below.
=> Work around for bug #27

SALib/analyze/morris.py, SALib/tests/test_analyze_morris.py
This closes #45.
Still need to write tests for `compute_mu_star_confidence()`.
=> Vectorised mu_star_confidence

LICENSE.md, README.md, SALib/analyze/morris.py, SALib/analyze/sobol.py, SALib/sample/morris.py, SALib/util/__init__.py, examples/sobol/sobol.py
* vectorize sobol bootstrap calculation and clean up #47 
* update license for future versions #53 
* universal line endings bug #43
=> some small improvements and bugfixes

index.html
Fixes broken links for:
* contributing
* advanced readme
Closes issue #56.
[ci skip]
=> Fixed broken links #56

LICENSE.md, README.md, setup.py
=> small updates to config files

SALib/analyze/morris.py, SALib/sample/optimal_trajectories.py, SALib/tests/test_analyze_morris.py
=> Solves #65

SALib/analyze/morris.py, SALib/sample/morris_util.py, SALib/sample/optimal_trajectories.py, SALib/tests/test_morris_util.py, SALib/tests/test_optimal_trajectories.py
=> Solution for issue #68 where duplicate trajectories cause problems with optimal trajectories

SALib/analyze/sobol.py
Shared memory parallel version of Sobol analysis. Tested with Ishigami function.
=> Parallel Sobol

.checkignore, README.md
Adds another code checking tool QuantifiedCode to the repository to help maintain the code quality.
=> Use Quantified code to monitor code quality

README.md, SALib/_version.py, SALib/analyze/delta.py, SALib/analyze/dgsm.py, SALib/analyze/morris.py, SALib/analyze/sobol.py, SALib/plotting/morris.py, SALib/sample/morris.py, SALib/sample/morris_util.py, SALib/test_functions/Sobol_G.py
a few odds and ends suggested by quantcode. I skipped a few of them that seemed like they would hurt readability even if they're technically correct.
=> Quantcode patches

SALib/analyze/morris.py, SALib/analyze/sobol.py, SALib/sample/morris.py, SALib/sample/saltelli.py, SALib/tests/test_morris.py, SALib/tests/test_regression.py, SALib/tests/test_util.py, SALib/util/__init__.py
Incorporates all updates from #94 and some tests.
@calvinwhealton check it out and see what you think. As far as I can tell, it still does all the same stuff. I really appreciate the additions.
@willu47 please take a look at this too, because I changed the way that read_param_file creates groups. But only internally, I don't think any external API should change. Generating the matrix is now done separately. The goal for this was to make sure that read_param_file will return a dictionary that's exactly the same format as the "problem dictionary" that someone would use instead of the param file.
Once we get this merged, there will be a good chance to get nonuniform distributions set up for all of the methods. 
Thanks!
=> Sobol groups and distributions

README.md
Replaces the v1.0.2 specific DOI with a link to the _latest_ DOI
=> Updated doi badge

CITATIONS.rst
Added links to the libraries which depend upon SALib [ci skip].
=> Added new libraries which use SALib to citations file

CHANGES.rst, tests/travis_install.sh
=> Release v1.1.0

SALib/analyze/delta.py, SALib/analyze/dgsm.py, SALib/analyze/fast.py, SALib/analyze/ff.py, SALib/analyze/morris.py, SALib/analyze/rbd_fast.py, SALib/analyze/sobol.py, SALib/util/__init__.py, SALib/util/results.py, requirements.txt, tests/test_to_df.py
Working example to address the functionality I requested in Issue #213 for the Sobol method
Usage example:
```
import pandas as pd
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
X = saltelli.sample(problem, 1000)
Y = Ishigami.evaluate(X)
Si = sobol.analyze(problem, Y, print_to_console=True)
first, (idx, second) = sobol.Si_to_pandas_dict(Si, problem)
first_Si = pd.DataFrame(first, index=problem['names'])
second_Si = pd.DataFrame(second, index=idx)
```
=> Function to create Pandas friendly dictionary

SALib/analyze/delta.py
Raise error with message indicating sample size may be too small
Address PR #152
=> Raise error if singular matrix is detected

SALib/test_functions/Ishigami.py, examples/sobol/sobol.bat, examples/sobol/sobol.py, examples/sobol/sobol.sh
Provide more context to examples to head off minor confusion regarding expected results and how to get these (e.g. #224)
=> Context for expected Ishigami results

examples/rbd_fast/rbd_fast.bat, examples/rbd_fast/rbd_fast.py, examples/rbd_fast/rbd_fast.sh, src/SALib/analyze/rbd_fast.py, tests/test_regression.py, tests/test_to_df.py
Changes to address #238 - reordered rbd-fast parameters and adjusted relevant examples/tests
=> Changed parameter args to conform with expected order

src/SALib/plotting/bar.py, src/SALib/util/results.py, tests/sample/morris/test_morris.py, tests/sample/morris/test_morris_strategies.py
Convenience plotting functionality as discussed in #257 
Manually tested with available examples and can confirm plots are produced for all analysis methods.
=> Basic convenience visualizations

src/SALib/analyze/dgsm.py
Please forgive the noise - this PR has some extremely minor code formatting changes, and removal of some minor repetitious calculations and function calls.
It didn't fit into the purpose of the earlier PR but it's been sitting in a branch by itself for quite some time now.
=> Minor dgsm method cleanup

src/SALib/analyze/morris.py, src/SALib/util/__init__.py
Expanded and corrected order of parameters in docstrings
Removed unnecessary parameter instantiation.
Sorry for the noise - these minor changes have been hanging around for a long time
=> Morris docs

src/SALib/analyze/delta.py, src/SALib/analyze/dgsm.py, src/SALib/sample/finite_diff.py, src/SALib/sample/latin.py, src/SALib/util/__init__.py
Additional changes for performance for delta and DGSM methods. 
Reduction in run time by up to 30%
=> Further performance improvements

src/SALib/test_functions/Sobol_G.py, tests/test_test_functions.py
Shift and curvature parameters are added.
Taken from Saltelli et al. (2010). 
Reference in docstring.
Changed docstring.
=> Changed Sobol G-function to modified G-function

tests/test_regression.py
Relaxed test conditions to address failing test for #275
=> added tolerance to delta singular value matrix error test

.travis.yml
=> Update travis config to use jobs and stages

.gitignore, CHANGELOG.rst, setup.cfg, src/SALib/analyze/sobol.py, src/SALib/sample/morris/__init__.py, src/SALib/sample/morris/brute.py, src/SALib/sample/morris/gurobi.py, src/SALib/sample/morris/local.py, src/SALib/sample/morris/strategy.py, src/SALib/util/__init__.py, src/SALib/util/results.py
A few miscellaneous warnings fixed.
=> Address deprecation, sphinx and syntax warnings

src/SALib/sample/saltelli.py
Hello, guys. I addressed the problem in issue #316. I made the commit directly in the master, since this is a minor change. I hope you don't mind.
Closes #316
=> Made skip_values an argument in function sample, module saltelli.py.

src/SALib/sample/latin.py, src/SALib/util/__init__.py
=> Latin sampler now works with different distributions

src/SALib/sample/finite_diff.py
Added type hinting and modified docstrings
=> Use of skip_values as an optional parameter for finite_diff

src/SALib/test_functions/lake_problem.py
In progress implementation of the Lake Problem from reference below to potentially resolve #309 
Hadka, D., Herman, J., Reed, P., Keller, K., (2015).
"An open source framework for many-objective robust decision making."
Environmental Modelling & Software 74, 114–129. 
doi:10.1016/j.envsoft.2015.07.014
I believe the function itself is working correctly, need to write accompanying tests, examples, and clean up documentation.
=> Example lake problem

src/SALib/analyze/sobol.py, src/SALib/util/__init__.py
Initial fix for parameter grouping and DF printing
=> Generalized group name extraction (Sobol)

src/SALib/analyze/morris.py, src/SALib/sample/morris/morris.py, src/SALib/util/__init__.py, tests/sample/morris/test_morris.py, tests/test_analyze_morris.py
Replaces PR #328 with apologies to @lbteixeira - needed to clear some conflicts
=> Merge lbteixeira refactor 327

src/SALib/analyze/ff.py, src/SALib/analyze/morris.py, src/SALib/sample/ff.py, src/SALib/sample/morris/brute.py, src/SALib/sample/morris/local.py, src/SALib/sample/morris/strategy.py, src/SALib/scripts/salib.py, src/SALib/util/__init__.py, src/SALib/util/util_funcs.py
Replace all list of "Arguments" with lists of "Parameters"
=> Standardize "Arguments" to "Parameters"

src/SALib/analyze/morris.py, src/SALib/analyze/sobol.py, src/SALib/sample/fast_sampler.py, src/SALib/sample/ff.py, src/SALib/sample/finite_diff.py, src/SALib/sample/latin.py, src/SALib/sample/morris/morris.py, src/SALib/sample/saltelli.py, src/SALib/util/__init__.py, src/SALib/util/util_funcs.py, tests/sample/morris/test_morris.py, tests/test_util.py
Fix/avoid errors that arise when all parameters are assigned to 1 group
=> Handle constant value groups

src/SALib/analyze/sobol.py
Non-matching order results in NaNs reported for S2
=> Fix out of order group names

examples/pawn/pawn.bat, examples/pawn/pawn.py, examples/pawn/pawn.sh, src/SALib/analyze/pawn.py, src/SALib/test_functions/Ishigami.py
Calculation is now vectorized and documented 
`A` and `B` parameters now accepted 
Added typing info for the function parameters.
=> Improved implementation of Ishigami function

src/SALib/util/problem.py
=> Simplifying ProblemSpec `to_df()`

FAQ.MD, examples/Problem/problem_spec.py
Temporarily pointing to examples in develop branch
=> Expanded FAQ

src/SALib/util/problem.py
Silly me - incorrectly removed code that had a purpose
=> Revert earlier commit to re-enable handling of multi-output results

examples/fast/fast.py, src/SALib/analyze/fast.py, src/SALib/analyze/rbd_fast.py, src/SALib/sample/fast_sampler.py, tests/test_cli.py, tests/test_cli_analyze.py, tests/test_to_df.py
=> Confidence interval estimation for FAST-based methods

FAQ.MD, examples/Problem/multi_output.py, examples/Problem/problem_spec.py, src/SALib/analyze/delta.py, src/SALib/util/problem.py, src/SALib/util/results.py
Fixed minor typo in FAQ as well.
=> Additional plotting support and result printing for dev branch

src/SALib/sample/latin.py, src/SALib/util/util_funcs.py, tests/sample/test_latin.py
Allows the latin sampler to be used with groups.
=> Added groups to Latin Hypercube sampler

tests/test_cli_analyze.py
Initial changes to move away from checking for exact value matches which may change depending on the RNG.
=> Move towards property-based testing rather than checking for exact values

src/SALib/util/util_funcs.py, tests/test_cli.py
=> Address dynamic test methods breaking tests

CITATIONS.rst
See here about how agentpy uses the SALib package: https://agentpy.readthedocs.io/en/latest/reference_analysis.html#agentpy.sensitivity_sobol
=> Add agentpy package to software list

examples/Problem/problem_spec.py, src/SALib/util/problem.py, tests/test_groups.py, tests/test_problem_spec.py
Minor fix to ProblemSpec example and additional tests to ensure a valid spec is being passed in
=> Additional checks for ProblemSpec definition

README.rst, src/SALib/analyze/fast.py, src/SALib/sample/fast_sampler.py
Hotfix to clarify docs for main branch
=> Updated docstrings for FAST (main branch)

src/SALib/analyze/pawn.py
Tests rely on PAWN indices to be in line with reported expected values for the Ishigami test function
(in https://doi.org/10.1016/j.envsoft.2018.07.019)
Replaces #366 and resolves #123
=> PAWN method with improvements

examples/sobol/sobol.py, src/SALib/analyze/sobol.py, src/SALib/plotting/bar.py, src/SALib/sample/finite_diff.py, src/SALib/sample/saltelli.py, tests/test_cli_analyze.py, tests/test_to_df.py
PR for Issue #414
@tupui - This PR raises a FutureWarning indicating that possible issues may arise in cases where the requirements are not met.
This is to allow older code to continue to function for now.
v1.4 onwards will instead raise a ValueError.
=> Sobol sequence fix #414

CHANGELOG.rst
Expect this to be the last update before v1.4 release
=> Update to v1.3.13

.zenodo.json
A good opportunity to update our metadata - to link author involvement with the software to our OrcidIDs.
Let me know your ORCID ID:
@ANtlord 
@cmutel 
@ecederstrand 
@dhadka 
@celliern 
@bsteubing 
@calvinwhealton 
@ConnectedSystems
=> Adds zenodo metadata file with author OrcidID

src/SALib/analyze/sobol.py, tests/test_sobol.py
Fix for https://github.com/SALib/SALib/issues/422.
=> bug_422: Fix sobol conf_level range check

README.rst, docs/index.rst
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
=> travis-ci.org -> travis-ci.com

setup.cfg
=> Add wheel package as required for installation

src/SALib/sample/saltelli.py
Resolves #442 
Update `skip_values` default to 0, and expand documentation to detail the reasoning, alongside references that point to more context/information.
To avoid `math.log` raising a ValueError, I simply wrapped the convergence check to only run in cases where `skip_values` is > 0.
Thanks to @stelong for raising the issue.
=> Change default skip_values option to 0 and expand documentation

src/SALib/sample/saltelli.py
Changes to clarify recent changes to Saltelli in light of #447, and indicate recommendations
@chahank - I would appreciate some feedback if you are able.
=> Adjust Saltelli documentation for clarity

src/SALib/analyze/pawn.py
=> Fix for #453 - Error when encountering empty slices

src/SALib/test_functions/Sobol_G.py, tests/test_test_functions.py
Incorporating suggested changes to address funky analytic results.
Resolves #335 #461
=> Update Sobol G-function analytic method (addresses #335 #461)

CHANGELOG.md
Additional changes continuing on from #462
=> Sobol intermediate resamples

docs/basics.rst
Apologies for the tiniest of PRs.
=> Docs: correct plural.

src/SALib/analyze/fast.py, src/SALib/analyze/rbd_fast.py, tests/test_analyze_fast.py, tests/test_cli_analyze.py
=> Fix for #480 - eFAST analysis erroring

src/SALib/analyze/morris.py, src/SALib/sample/morris/local.py, src/SALib/sample/morris/morris.py
Expanded documentation for the Morris method (both sampling and analysis) as part of our drive to have more informative/beginner-friendly documentation.
=> Expanded Morris docs

src/SALib/analyze/pawn.py
The current implementation is naive in that the analysis is conducted on each factor within a group individually, and the mean of their results are reported. As such, grouping parameters incurs an additional computational cost contrary to the behavior of grouped parameters with other approaches.
Negative values do not affect the reported results given the PAWN index is bounded between 0 and 1.
=> Support for grouped parameters with the PAWN method

docs/conf.py
Follow up of #523 
The config was pointing to my branch for testing. This points to `main`.
=> Update version switcher

src/SALib/analyze/delta.py
Submitting tweak to DMIM implementation to handle zero variance case.
Closes #344
=> Handle DMIM zero variance case

src/SALib/analyze/hdmr.py
Updated hdmr docstring with the new pydata sphinx theme.
=> HDMR Docstring

.gitignore, CONTRIBUTING.md, docs/api.rst, src/SALib/analyze/delta.py, src/SALib/analyze/dgsm.py, src/SALib/analyze/fast.py, src/SALib/analyze/ff.py, src/SALib/analyze/hdmr.py, src/SALib/analyze/morris.py, src/SALib/analyze/pawn.py, src/SALib/analyze/rbd_fast.py, src/SALib/analyze/sobol.py, src/SALib/plotting/bar.py, src/SALib/sample/morris/morris.py
Minor changes for readability and accessibility
=> Pre-release documentation updates

src/SALib/sample/sobol.py
=> Fix skip_values integer check

src/SALib/sample/sobol.py, tests/test_sp_sobol.py
Closes #545
Definitely need to change the tests to run this instead of the older Saltelli sampler.
=> Fix log2 in Sobol' exponent check

README.rst, docs/index.rst, pyproject.toml, src/SALib/analyze/rsa.py, src/SALib/util/problem.py, tests/test_problem_spec.py
@tupui Available for a quick review?
```python
import numpy as np
from SALib.test_functions import Ishigami
from SALib import ProblemSpec
def linear(x, a, b):
"""Return y = a + b + x"""
return a + b + x
def wrapped_linear(abx):
a, b, x = abx.T
return linear(x, a, b)
sp = ProblemSpec({
'names': ['a', 'b', 'x'],
'bounds': [
[-1, 1],
[-1, 2],
[-3, 1],
],
})
ax = (
sp.sample_sobol(2**10)
.evaluate(wrapped_linear)
.analyze_rsa(bins=20)
).plot()
ax[0].set_title("Linear");
```
```python
sp = ProblemSpec({
'names': ['x1', 'x2', 'x3'],
'bounds': [(-np.pi, np.pi), ] * 3,
'outputs': ['Y']
})
ax = (
sp.sample_sobol(2**10)
.evaluate(Ishigami.evaluate)
.analyze_rsa(bins=20)
).plot();
ax[0].set_title("Ishigami");
(
sp.sample_sobol(2**10)
.evaluate(Ishigami.evaluate)
.analyze_rsa(bins=20, target="X") …
```
=> Add Regional Sensitivity Analysis

src/SALib/util/problem.py
=> Better, and explicit, support for IPython console display

docs/developers_guide.md, docs/user_guide/wrappers.rst, src/SALib/util/problem.py
Resolves #560
Replaces misleading/incorrect statement with a fully fleshed out example of how to modify wrappers to allow for parallel evaluation/analysis.
Added additional detail on suitable project structure.
Thanks again to @morrowcj for catching this
=> Update misleading docs

src/SALib/analyze/delta.py
=> Use reduced-size sample set for bootstrap estimation (delta, sobol)

CONTRIBUTING.md
The case of the file extension was inconsistent.
=> Fix cross-reference to CHANGELOG.md in CONTRIBUTING.md

src/SALib/analyze/enhanced_hdmr.py, src/SALib/analyze/sobol.py, src/SALib/sample/sobol.py
=> Update documentation following suggestion in #603

src/SALib/plotting/heatmap.py, src/SALib/sample/saltelli.py
=> Fix incorrect group display in heatmap plots

src/SALib/analyze/morris.py, src/SALib/analyze/pawn.py, src/SALib/analyze/rsa.py, src/SALib/analyze/sobol.py, src/SALib/plotting/hdmr.py, src/SALib/plotting/heatmap.py, src/SALib/sample/morris/morris.py, src/SALib/util/__init__.py, src/SALib/util/problem.py, src/SALib/util/util_funcs.py
There is at least two slightly different ways in which grouped factors are being handled. 
The changes in this PR consolidates the majority into a single function, leveraging the `pandas` provided `unique()` method.
This partly resolves #614
=> Consolidate handling of grouped factors into a single approach

.github/workflows/release.yaml, AUTHORS.rst, CONTRIBUTING.md
My mistake, I forgot to update the instructions.
I also just saw the Authors file. Not sure if we should keep it, I added myself there for now then 😅 
Otherwise we might want to fill the changelog in a follow up.
=> Update maintainer docs

src/SALib/analyze/delta.py, src/SALib/analyze/morris.py, src/SALib/analyze/sobol.py, src/SALib/test_functions/Sobol_G.py, src/SALib/util/__init__.py, tests/sample/test_latin.py, tests/test_analyze_morris.py, tests/test_regression.py, tests/test_to_df.py
Removes use of deprecated/removed numpy methods to be compatible with numpy 2.0
Closes #625
=> Updates for numpy 2.0

src/SALib/analyze/pawn.py, tests/test_analyze_pawn.py
At in title.
I wrote the bare minimum test file just to be sure this particular bug is fixed. 
Close #635
=> Fix pawn analysis for problems with groups

AUTHORS.rst, pyproject.toml
Minor changes to remove outdated info
=> Remove outdated info

docs/user_guide/advanced.rst, src/SALib/util/__init__.py
=> DOC: Change truncnorm bounds order

src/SALib/analyze/dgsm.py
This PR fixes an issue #654 related to example for DGSM analyze function.
=> fix: dgsm analyze example doc
