SALib/SALib

.coveragerc, .travis.yml, SALib/sample/morris.py, SALib/sample/morris_util.py, SALib/sample/optimal_trajectories.py, SALib/tests/test_morris.py, SALib/tests/test_morris_util.py, SALib/tests/test_optimal_trajectories.py, SALib/util/__init__.py, setup.py
Includes:
* corrected bug #49 and #48 and refactored morris_optimal code to integrate combinatorial optimisation (#17) and brute force methods
* new tests for combinatorial optimisation are skipped unless the gurobipy module is present
* amended setup.py to include gurobipy as extra_requirement
* few other small admin changes 
NB, supersedes #50 which should be closed without merging
=> Adds the combinatorial optimisation feature as an optional dependency

CONTRIBUTING.md, README-advanced.md, SALib/tests/test_regression.py, SALib/tests/test_sobol.py, examples/sobol/sobol.py, examples/sobol/sobol.sh
Ok this should be ready now. A couple of tests to improve coverage of the analyze.sobol function, with/without the parallel option. Also updates examples accordingly.
I'll assume this is ok to merge since it doesn't change any functionality, but let me know if anyone notices something off about it.
=> simple regression test for parallel sobol

SALib/analyze/sobol.py, SALib/sample/saltelli.py, SALib/util/__init__.py
The changes are in two separate areas: group sampling for Sobol sensitivity analysis and conversion of uniform 0-to-1 uniform variables into other distributions. More detailed descriptions are provided below. 
Group sampling for Sobol indices makes changes to the files saltelli.py and sobol.py. In saltelli.py, the sample function was modified to add a condition for if group sampling is desired (default groups=False). If this is the case the code uses the previous method. If group sampling is desired, then instead of looping over parameters when cross-sampling the matrices, groups are looped-over with a nested loop to account for the variables within each group. The size of the matrices also changes because instead of 'D' variables in the previous code there are now 'Dg' groups. The change …
=> Group Sampling for Sobol Analysis and Conversion to Non-Uniform Distributions

LICENSE.md, README.md, SALib/analyze/morris.py, SALib/analyze/sobol.py
A couple of small changes to clean up before we release an updated version.
* Fixes #127 (using `problem.get('groups')` in analyze.morris)
* Fixes #114, and by extension #109, by normalizing the model output in analyze.sobol using the suggestion by @sofianehaddad (`Y = (Y - Y.mean()) / Y.std()`)
=> Bugfix 114 and 127

.travis.yml
As suggested by @willu47 in #142 
Have not tested this, because it will only deploy from master. We'll have to merge and then test it by pushing some tags:
```
git tag v1.0.x
git push --tags
```
(at least this is how I've been doing it -- there is probably a better way)
=> continuous deployment when tags pushed

SALib/sample/morris/__init__.py
Fixes #103 - the size of the Morris sample depends on the number of parameters *or* groups, and the number of trajectories *or* optimal trajectories, depending on whether groups are used, optimal trajectories are used.
=> Updated morris docstring with groups and optimal trajectories

README.md, docs/basics.rst, docs/conf.py, docs/getting-started.rst
Addresses #155 
In the readme I just changed them to the non-default options. This way it still explains what the argument does without being redundant.
In the docs I removed the kwargs from the function call and describe them in the text instead.
=> do not use default kwargs in docs and readme examples

README-advanced.md, README.md, SALib/analyze/morris.py, SALib/analyze/sobol.py, SALib/sample/morris/__init__.py, SALib/sample/morris/brute.py, SALib/sample/morris/gurobi.py, SALib/sample/morris/local.py, SALib/sample/morris/strategy.py, SALib/sample/saltelli.py, SALib/util/__init__.py, tests/sample/morris/test_morris.py, tests/sample/morris/test_morris_strategies.py, tests/test_util.py
Addresses #161, there was some confusion in the purpose and syntax of parameter groups.
* added a section to advanced readme
* fixed docstring for the `read_param_file()` function in `util/__init__.py`
* removed redundant input parameter `num_vars` from `compute_groups_matrix` function in the same file, and changed all calls to this function throughout. (The number of variables is always the length of the list of group names, which is the other input)
No changes to dependencies, so not sure why the dependency-ci error below.
=> Patch docs groups

SALib/analyze/fast.py, SALib/sample/fast_sampler.py
Addresses two bug fixes mentioned in #162 for FAST
- Sample size requirement should be N > 4M^2
- In `compute_first_order` and `compute_total_order` functions, the array length of `Sp` should use the `math.ceil` function instead of `int`, round up instead of down from `N/2`
=> bug fixes to FAST (#162)

setup.cfg
I think this will resolve the deployment error at the end of #162 ... looks like Travis does not expect quotes or commas anymore, and adds the quotes instead.
Edit: this is only a guess and might not be correct. Is there a way to see if it works without merging first?
=> remove quotes and commas from setup.cfg classifiers

SALib/test_functions/Sobol_G.py
Hey,
Not much of an error, but could be helpful for a user to know that you meant 'zero' here :)
Have a nice day!
=> fix for 'one' instead of 'zero' in ValueError text

SALib/analyze/rbd_fast.py
Fix typo in RBD-fast docstring (see [issue 200](https://github.com/SALib/SALib/issues/200))
=> fix doc typo (default interference parameter)

SALib/analyze/morris.py, SALib/plotting/morris.py, SALib/sample/morris/__init__.py, SALib/sample/morris/brute.py, SALib/sample/morris/gurobi.py, SALib/util/__init__.py, examples/morris/morris.py, examples/morris/morris.sh, tests/sample/morris/test_gurobi.py, tests/sample/morris/test_morris.py, tests/sample/morris/test_morris_strategies.py, tests/test_analyze_morris.py, tests/test_regression.py, tests/test_util.py
Fixes #209 
**This changes the interface to the morris method - removing an argument.  I haven't used Deprecation warnings, and we should decide what to do before merging/releasing this.**
* provides default value for `levels` parameter (4)
* removes the `grid_jump` parameter from sample and analyze implementations of Morris.  The code now automatically calculates delta from the number of levels and this removes the need for a grid_jump parameter
* removed the duplicate implementation of Morris in preference of the (better tested) groups method, which is overridden by parameters when not using groups.
=> Fixes inconsistent use of grid_jump and delta in Morris implementations

.travis.yml
Travis have updated the system version of Python that they use and this has caused our tests to fail.
=> Travis: don't use python system site packages

src/SALib/plotting/morris.py, src/SALib/sample/morris/__init__.py, src/SALib/sample/morris/brute.py, src/SALib/sample/morris/local.py, src/SALib/test_functions/Sobol_G.py
Minor changes to improve computational time performance.
Benchmarking using the package example for the Morris method shows decrease in runtime from 2.64 seconds to 1.95 seconds (~25% improvement).
All tests passed and output remains the same.
Further improvements possible by moving performance critical code to Cython or Numba as discussed [here](https://github.com/SALib/SALib/issues/234#issuecomment-500762392).
=> Morris - Minor performance enhancements

src/SALib/analyze/delta.py, src/SALib/analyze/fast.py, src/SALib/sample/common_args.py, src/SALib/sample/fast_sampler.py, src/SALib/sample/ff.py, src/SALib/sample/finite_diff.py, src/SALib/sample/latin.py, src/SALib/sample/morris/__init__.py, src/SALib/sample/saltelli.py
Previous PR (#222) sought to simplify usage via the terminal/console but left clean up to a later date.
I have now gone through and removed duplicated and irrelevant options for the available sampling methods.
=> Remove duplicated CLI options

docs/Makefile, docs/conf.py, docs/license.rst, setup.cfg, setup.py, src/SALib/__init__.py
The current pyscaffold contains a vendored version of `setuptools_scm` that contains a bug in `list_files_in_archive` when the `setuptools` 41.2.0 `walk_revctrl()` function is called with default args. This breaks pip installation of random other packages in your requirements.txt with the following output because setuptools_scm registers itself as a plugin to setuptools:
```
writing pip-egg-info/python_bioformats.egg-info/PKG-INFO
writing requirements to pip-egg-info/python_bioformats.egg-info/requires.txt
writing top-level names to pip-egg-info/python_bioformats.egg-info/top_level.txt
writing dependency_links to pip-egg-info/python_bioformats.egg-info/dependency_links.txt
*** FileNotFoundError: [Errno 2] No such file or directory: ''
```
=> Bump pyscaffold version

.travis.yml, CONTRIBUTING.md, docs/getting-started.rst, setup.cfg
Allow failure on Py3.5 - build is failing due to the use of features only found in Py3.6
Use of `python setup.py test` raises deprecation warning. Switched to `pytest` to resolve.
Updated documentation to match
=> Update travis and package config

src/SALib/sample/morris/__init__.py
Somehow missed this in the earlier refactoring - the morris sampling method did not support seed setting.
=> Add missing seed option for morris sampling

src/SALib/analyze/delta.py, src/SALib/analyze/dgsm.py, src/SALib/analyze/morris.py
Change default num_resamples values for Delta, DGSM and Morris to identical default num_resamples of 100 samples, which Closes #291
=> Identical default num_resamples for delta, dgsm and morris #291

src/SALib/analyze/delta.py
A "TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer." is thrown by numpy >1.18 in the linspace function in the delta analysis. `int(round(M))` should fix this issue.
=> Numpy >1.18 compatibility

src/SALib/plotting/morris.py
Quick changes to docstring and function parameters to address potential confusion around `param_dict` vs the SALib problem specification, exemplified by the issue raised in #282
=> Make use of `param_dict` optional and change parameter name to `opts`

src/SALib/util/problem.py
Allow easier reuse of existing samples and results
```python
sp.samples = existing_saltelli_samples
sp.results = existing_model_results
sp.analyze_sobol()
```
=> Add setters for sample and result properties

docs/advanced.rst
=> Fix typo: `dist` should be `dists`

docs/index.rst
Minor typo, noticed it while browsing the docs
=> Fix minor type in RBD-FAST Tarantola reference hyperlink

README.rst, examples/Problem/problem_spec.py, examples/rbd_fast/rbd_fast.py, src/SALib/analyze/fast.py, src/SALib/sample/fast_sampler.py
Clarify in docstring which FAST method is implemented, which caused some confusion (https://github.com/SALib/SALib/issues/404)
Closes #404
=> Docstring fixes for (e)FAST method

src/SALib/util/__init__.py, tests/sample/morris/test_morris.py
=> Target warning message check and address deprecated use of np.int (fix for #425)

examples/Problem/multi_output.py, examples/Problem/problem_spec.py, src/SALib/analyze/sobol.py, src/SALib/test_functions/lake_problem.py, src/SALib/util/problem.py, tests/test_cli_analyze.py, tests/test_problem_spec.py
Adds an `analyze_parallel` method, and cleans up REPL representation.
This PR is currently in progress, tests to ensure results are identical to the sequential approach are being finalized.
Closes #456 
UPDATE: 
This PR incorporates several inter-related changes which I did a poor job of keeping separate. Given the related nature of the changes however, I think it is acceptable.
1. The base `evaluate` and `analyze` methods now support the `nprocs` keyword argument. If provided, the method simply redirects the call to the `evaluate_parallel` and `analyze_parallel` methods. The motivation for maintaining the separation is primarily to reduce code clutter.
2.  Use of processors is capped to the available/detected cores (for model evaluation) and number of outputs (for analysis). i.e., no …
=> Parallel analysis

docs/advanced.rst, docs/api.rst, src/SALib/analyze/delta.py, src/SALib/analyze/dgsm.py, src/SALib/analyze/fast.py, src/SALib/analyze/ff.py, src/SALib/analyze/hdmr.py, src/SALib/analyze/morris.py, src/SALib/analyze/pawn.py, src/SALib/analyze/rbd_fast.py, src/SALib/analyze/sobol.py, src/SALib/sample/finite_diff.py, src/SALib/test_functions/lake_problem.py
Noticed that the compatible methods are not correctly displayed when rendered on readthedocs:
```
Compatible with
------------------
* `morris`
```
Turns out Sphinx pre-defines section headers and does not render custom ones.
To resolve this, I've merged the listings under the "Notes" section.
I plan to place further text on method caveats, pitfalls, and other useful information (as done for the Saltelli method).
```
Notes
-----
Compatible with:
`morris` : :func:`SALib.sample.morris.sample`
```
PR includes miscellaneous clean up (primarily removing whitespace, and other changes to conform to PEP8).
=> Improve listing of compatible sampling methods

src/SALib/util/problem.py, tests/test_problem_spec.py
Resolves #483 
Raises error to alert user that there is no point in conducting SA for a single parameter.
This targets OO-based interface only.
=> Raise error when a single parameter/group is detected [OO-based only]

README-advanced.md, docs/advanced.rst, src/SALib/util/__init__.py
Hi, Please consider this improved triangular distribution syntax for Sobol Sensitivity Analysis, previously user was forced to start at 0 when specifying triangular distribution. Now we can start at any number >0.
Need to Update the Docs: First Parameter is now Triangular Distribution Start, Second Parameter is Triangular Distribution End, 3rd parameter is position of Peak.
=> Better Triangular Distribution

examples/Problem/problem_spec.py, pyproject.toml, src/SALib/util/problem.py
Closes #521
This removes the dependency to Pathos to make it optional.
We could also do something similar for `multiprocess` (which is pulled by `Pathos` at the moment and used for parallel execution.). In that case, it should be fairly easy to write compatible code that would use `multiprocess` if installed and fallback to `multiprocessing` if not.
I am not sure about how the packaging is handled, so I did not update for now the requirements files (and I would suggest moving to something simpler like `flit` or `hatch` which is now the recommendation for pure Python packages (see https://packaging.python.org/en/latest/tutorials/packaging-projects/), I can do the lifting here if wanted).
=> Make Pathos optional

src/SALib/sample/saltelli.py, src/SALib/sample/sobol.py
Closes #486, closes #450 and should close #478 as if the method does work better (which I am not convinced yet from my tests) should go in SciPy directly.
Following discussions in #486, this adds Sobol' sampler as a new sampler and deprecate `salib.sample.saltelli`.
Note that SciPy also has LHS (and Halton that can be used otherwise).
This needs SciPy to 1.7 and doing so I updated NumPy and Python minimal versions following NEP29.
This is a draft as I need some guidance on how to proceed next. E.g. I removed the skipping as we can scramble and should have better properties doing so.
cc @ConnectedSystems
=> Add Sobol' sampler from SciPy

src/SALib/sample/sobol.py
Need to allow setting a seed value via the CLI.
This was disabled for the Saltelli sampling method as it did not use a seed, but is necessary to make scrambled sequences deterministic.
Quick and easy change, missed this in the first PR.
=> Allow seed as CLI option

src/SALib/util/__init__.py
Allow specified bounds to be equal to zero when defining triangular distributions
=> Triang dist bounds fix

.pre-commit-config.yaml
Flake8 was moved from GitLab to GitHub. Hence the CI failing.
=> Update flake8 repository

tests/test_problem_spec.py
As seen in CI here: https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315
```
FAILED tests/test_problem_spec.py::test_parallel_single_output - AssertionError: 
[383](https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315#step:9:384)
Arrays are not equal
[384](https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315#step:9:385)
[385](https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315#step:9:386)
Mismatched elements: 82 / 2048 (4%)
[386](https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315#step:9:387)
Max absolute difference: 3.55271368e-15
[387](https://github.com/SALib/SALib/actions/runs/3864699280/jobs/6587685315#step:9:388)
Max relative difference: 3.64569322e-15 …
```
=> Lower tolerance in test_parallel_single_output test

src/SALib/analyze/hdmr.py, tests/test_problem_spec.py
**hdmr** method was throwing a `keyerror` for `c2` if `maxorder = 1`
`keyerror` and corresponding `referencing before assignment` fixed.
=> hdmr maxorder=1 fix

src/SALib/plotting/hdmr.py
Legend subscripts were not correctly displayed if `num_vars>10`. This should fix that.
For testing, modify line 14 in _**examples\hdmr\hdmr.py**_ as:
`problem = {"num_vars": 11, "names": ["x1", "x2", "x3","x4","x5","x6","x7","x8","x9","x10","x11"], "bounds": [[-np.pi, np.pi]] * 11}`
=> legend subscript fix for num_vars>10

src/SALib/analyze/rsa.py
Minor corrections:
- referred to incorrect function argument
- Replace markdown syntax with reST
Took the opportunity to replace min-max scaling with a simple max scaling to align with the upcoming discrepancy analysis method (poor practice to mix changes in a single PR I know, but it's a tiny change).
=> Correct typo in RSA docstrings

docs/index.rst
The current URL is making a lot of re-directions which is preventing the badge from loading correctly on Safari.
Here I am changing the URLs to match latests instructions from JOSS: use the DOI for the target and the JOSS url for the image itself.
=> Update JOSS badge to fix Safari issue

docs/api.rst, docs/index.rst, src/SALib/analyze/discrepancy.py, src/SALib/analyze/morris.py, src/SALib/analyze/sobol.py, src/SALib/sample/morris/local.py, src/SALib/test_functions/lake_problem.py, tests/test_discrepancy.py
Add `SALib.analyze.discrepancy` which is the method described in https://arxiv.org/abs/2206.13470
Based on 2D sub projections of [Xi,Y], the discrepancy of each samples is calculated which gives a value for all Xi. This can be used as a sensitivity indice.
Opening this in draft to get early feedbacks on how to proceed next. It's mainly missing tests and doc, but the feature itself should already work.
cc @arnaldpuy
=> Add discrepancy analysis

README.rst, docs/index.rst, src/SALib/analyze/rsa.py
Remove normalization in Regional Sensitivity Analysis (as discussed in https://github.com/SALib/SALib/issues/587) and replace the Anderson-Darling test in favor of the Cramér-von Mises (CvM) test.
Normalization has the effect of making reported values sensitive to the maximum influence, making small values appear close to 0. Although these are smaller than the maximum, they could still indicate large differences in the distributions.
The CvM test is used as it reports values between 0 and $+\infty$, avoiding negative values in cases where users would like to simply max-normalize.
=> Switch to Cramer-von Mises test for RSA, remove normalization (fix #587)

src/SALib/analyze/rbd_fast.py
While the file is script-like (has “`if __name__ == __main__:`” or otherwise has interesting side effects), the executable bit is not set in its filesystem permissions,so the shebang line is not useful. It can still be executed with “`python -m SALib.analyze.rbd_fast`”.
=> Remove a useless shebang line

docs/user_guide/getting-started.rst
This PR remove `from SALib.sample import saltelli` deprecated import statement
from Getting Started docs
=> Remove deprecated saltelli sample from start doc
